# Multiple Linear Regression

In [ ]:
# y = b0 + b1*x1 + b2*x2 .....
# here, it has many independent variables x1,x2,....

In [ ]:
# Assumptions of linear regression
# - linearity
# - homoscedasticity
# - multivariate normality
# - Independence of errors
# - Lack of multicollinearity
# these assumptions are just for knowledge, no need to be checked, bcoz even if these are not true,
# it would just result that model will perform poorly and we'll select another model techniques, as simple as that.

In [ ]:
# Dummy variable trap
# y = b0 + b1*x1 + b2*x2 + (1 categorical column with 2 categories)
#   = b0 + b1*x1 + b2*x2 + b3*D3 + b4*D4 (D3 & D4 are dummy vars & take values 0 & 1)
# however the above is wrong, bcoz since if D3 is 1, D4 is by default 0, and vice versa,
# so model can't interpret why D4 is necessary, as it is not giving any new info.
# So, "always omit 1 dummy variable in equation from the total no. of dummy vars"
# also, if D3 is 0, it might seem D4's coeff is lost, however b0 take care of it.

In [ ]:
# statistical significance
# when do we say that the following hypotheses is incorrect or correct for any problem
# depending on the probability or accuracy, if an outcome is beyond our defined alpha value 
# eg. alpha = 0.05 or 5%, that is if our likelihood crosses 95%, we say that our hypotheses was correct or incorrect
# P-value is the probability value of likelihood of the occurance of an event

In [ ]:
# 5 methods of building models
# 1. all-in
# 2. backward selection
# 3. forward selection
# 4. bidirectional elimination
# 5. score comparison
# 2,3,4 are also c/a 'stepwise regression'
# watch course video on 'section 7 - video 54.'

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

## Encoding categorical data

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [5]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
# No need to apply feature scaling, as there as coefficients in multiple linear regression equation to take care of it

## Training the Multiple Linear Regression model on the Training set

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# No new class, that same LinearRegression class identifies that there are several features in the dataset
# and performs the multiple regresssion

LinearRegression()

In [ ]:
# No need to do anything abt the dummy variable trap or significant p-value selection as the class of 
# multiple linear regression already has some methods take care of it & will auto-select 
# the best features to give highest accuracy

## Predicting the Test set results

In [ ]:
# we can't visualize the predicted results just like linear regression as there are several features
# so, we'll just visualize 2 vectors - predicted profits (y_pred) & 
# actual profits (y_test) of the testing dataset

In [11]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# np.set_printoptions - is to display the numerical values with just 2 decimal points
# concatenate func of numpy is used to visualize 2 vectors side-by-side
# np.concatenate((a1,a2),axis=0) ; a1 & a2 are vectors & axis=0 means horizontal while axis=1 means vertical
# reshape func is used to change the vector to vertical representation
# y.reshape(size of y,axis)

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [12]:
print(regressor.predict([[1, 0, 0, 160000, 130000, 300000]]))

# making a single prediction of california,R&D=160000,Admin=130000,marketing=300000. 
# Result is the predicted profit.
# predict func expects 2D array as input, hence double square brackets

[181566.92]


In [13]:
print(regressor.coef_)
print(regressor.intercept_)

# check the bonus ipynb to see the explaination for this.

[ 8.66e+01 -8.73e+02  7.86e+02  7.73e-01  3.29e-02  3.66e-02]
42467.529248549545
